FROM node:lts-buster-slim AS development

# Create app directory
WORKDIR /usr/src/app

COPY src/backend/package.json /usr/src/app/package.json
COPY src/backend/package-lock.json /usr/src/app/package-lock.json
RUN npm ci

COPY src/backend/. /usr/src/app

EXPOSE 3000

CMD [ "npm", "run", "dev" ]