# TODO: Will be separate azure pipeline to build and deploy later
stages:
- stage: Deploy
  displayName: Deploy application stage
  dependsOn: Build
  jobs:
  - job: Release
    displayName: Deploy k8s and application
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'manifests'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'

          - script: |
              ls -la $(System.ArtifactsDirectory)/manifests
              cat $(System.ArtifactsDirectory)/manifests/backend.yaml
              cat $(System.ArtifactsDirectory)/manifests/frontend.yaml

          - task: KubernetesManifest@0
            displayName: Deploy Backend to Kubernetes cluster
            inputs:
              action: deploy
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: 'aks-pisharp-dev-ase'
              namespace: backend
              manifests: |
                $(System.ArtifactsDirectory)/manifests/backend.yaml

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: 'aks-pisharp-dev-ase'
              namespace: frontend
              manifests: |
                $(System.ArtifactsDirectory)/manifests/frontend.yaml
